"""Summarize cross-seed parameter stability for paper parameterization runs.

This script focuses on two stability questions across multiple seeds:

1. Basin-wise parameter stability:
   For each method/parameter, compute the variance of the predicted parameter
   across seeds for the same basin, then average those basin variances.

2. Attribute-correlation stability:
   For each method/attribute/parameter, compute the seed-wise Spearman
   correlation between predicted parameters and basin attributes, then summarize
   cross-seed agreement using:
   - mean R^2
   - variance of R^2
   - sign consistency of rho
   - top-k overlap of the strongest attributes

The script expects the seed-level parameter table generated by
``project.parameterize.analyze_param_results`` plus the basin attribute table.
"""

from __future__ import annotations

import argparse
import itertools
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


DEFAULT_PARAMETER_CSV = "project/parameterize/analysis/predicted_parameters_by_seed.csv"
DEFAULT_ATTRIBUTE_CSV = "project/parameterize/analysis/basin_attributes.csv"
DEFAULT_OUTPUT_DIR = "project/parameterize/analysis/seed_stability"
DEFAULT_KEY_PARAMETERS = "smax,beta,perc,uzl,cfmax,route_b"
DEFAULT_MIN_MC_SAMPLES = 100

META_COLUMNS = {"basin_id", "variant", "seed", "sample_count"}
PARAMETER_ALIASES = {
    "smax": "parFC",
    "fc": "parFC",
    "beta": "parBETA",
    "k0": "parK0",
    "k1": "parK1",
    "k2": "parK2",
    "lp": "parLP",
    "perc": "parPERC",
    "uzl": "parUZL",
    "tt": "parTT",
    "cfmax": "parCFMAX",
    "cfr": "parCFR",
    "cwh": "parCWH",
}
VARIANT_ORDER = ["deterministic", "distributional", "mc_dropout"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare cross-seed stability across deterministic, distributional, and MC-dropout parameterization methods.",
    )
    parser.add_argument(
        "--parameter-csv",
        default=DEFAULT_PARAMETER_CSV,
        help="Seed-level predicted parameter table from analyze_param_results.py.",
    )
    parser.add_argument(
        "--attribute-csv",
        default=DEFAULT_ATTRIBUTE_CSV,
        help="Basin attribute table from analyze_param_results.py.",
    )
    parser.add_argument(
        "--output-dir",
        default=DEFAULT_OUTPUT_DIR,
        help="Directory where stability summaries will be written.",
    )
    parser.add_argument(
        "--focus-parameter",
        default="smax",
        help="Parameter to highlight in the report. Supports aliases such as smax -> parFC.",
    )
    parser.add_argument(
        "--key-parameters",
        default=DEFAULT_KEY_PARAMETERS,
        help="Comma-separated key parameters for the correlation stability overview figure.",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=5,
        help="Top-k strongest attributes used for overlap analysis.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=220,
        help="Figure DPI.",
    )
    parser.add_argument(
        "--min-mc-samples",
        type=int,
        default=DEFAULT_MIN_MC_SAMPLES,
        help="Minimum allowed MC-dropout sample_count in the seed-level parameter table.",
    )
    args = parser.parse_args()
    if args.top_k < 1:
        raise ValueError("--top-k must be at least 1.")
    if args.min_mc_samples < 1:
        raise ValueError("--min-mc-samples must be at least 1.")
    return args


def infer_parameter_names(parameter_frame: pd.DataFrame) -> list[str]:
    names = []
    for column in parameter_frame.columns:
        if column in META_COLUMNS:
            continue
        if column.endswith("_mean"):
            names.append(column[: -len("_mean")])
    if not names:
        raise ValueError("No parameter columns ending with '_mean' were found.")
    return names


def canonical_parameter_name(name: str, available: list[str]) -> str:
    normalized = name.strip()
    if normalized in available:
        return normalized

    lowered = normalized.lower()
    alias_match = PARAMETER_ALIASES.get(lowered, normalized)
    if alias_match in available:
        return alias_match

    for parameter in available:
        if parameter.lower() == lowered:
            return parameter

    raise ValueError(
        f"Unknown parameter '{name}'. Available parameters: {', '.join(available)}"
    )


def parse_key_parameters(raw_value: str, available: list[str]) -> list[str]:
    candidates = [value.strip() for value in raw_value.split(",") if value.strip()]
    if not candidates:
        raise ValueError("--key-parameters produced an empty list.")

    resolved: list[str] = []
    for candidate in candidates:
        canonical = canonical_parameter_name(candidate, available)
        if canonical not in resolved:
            resolved.append(canonical)
    return resolved


def sign_consistency_rate(values: pd.Series | np.ndarray) -> float:
    array = np.asarray(values, dtype=float)
    valid = array[~np.isnan(array)]
    if valid.size == 0:
        return np.nan

    signs = np.sign(valid)
    nonzero = signs[signs != 0]
    if nonzero.size == 0:
        return 1.0

    positive = np.sum(nonzero > 0)
    negative = np.sum(nonzero < 0)
    return float(max(positive, negative) / nonzero.size)


def mean_pairwise_topk_overlap(seed_rankings: dict[int, list[str]], top_k: int) -> float:
    if len(seed_rankings) < 2:
        return np.nan

    overlaps: list[float] = []
    for seed_a, seed_b in itertools.combinations(sorted(seed_rankings), 2):
        top_a = set(seed_rankings[seed_a][:top_k])
        top_b = set(seed_rankings[seed_b][:top_k])
        overlaps.append(len(top_a & top_b) / float(top_k))
    return float(np.mean(overlaps))


def overlap_rate(items_a: list[str], items_b: list[str], top_k: int) -> float:
    if top_k < 1:
        return np.nan
    set_a = set(items_a[:top_k])
    set_b = set(items_b[:top_k])
    return len(set_a & set_b) / float(top_k)


def sign_agreement_rate(values_a: pd.Series | np.ndarray, values_b: pd.Series | np.ndarray) -> float:
    array_a = np.asarray(values_a, dtype=float)
    array_b = np.asarray(values_b, dtype=float)
    valid = ~(np.isnan(array_a) | np.isnan(array_b))
    if not np.any(valid):
        return np.nan

    signs_a = np.sign(array_a[valid])
    signs_b = np.sign(array_b[valid])
    agreement = signs_a == signs_b
    return float(np.mean(agreement))


def validate_mc_dropout_sample_counts(parameter_frame: pd.DataFrame, min_samples: int) -> dict[str, int]:
    sample_summary: dict[str, int] = {}
    for variant, variant_frame in parameter_frame.groupby("variant"):
        if "sample_count" not in variant_frame.columns:
            continue
        sample_summary[variant] = int(variant_frame["sample_count"].min())

    mc_min = sample_summary.get("mc_dropout")
    if mc_min is None:
        raise ValueError("No mc_dropout rows were found in the parameter table.")
    if mc_min < min_samples:
        raise ValueError(
            f"mc_dropout sample_count must be at least {min_samples}, but the minimum observed value is {mc_min}."
        )
    return sample_summary


def basin_variance_table(
    parameter_frame: pd.DataFrame,
    parameter_names: list[str],
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    basin_rows: list[dict[str, float | int | str]] = []
    parameter_rows: list[dict[str, float | int | str]] = []

    for variant, variant_frame in parameter_frame.groupby("variant"):
        for parameter in parameter_names:
            value_column = f"{parameter}_mean"
            pivot = variant_frame.pivot_table(
                index="basin_id",
                columns="seed",
                values=value_column,
                aggfunc="mean",
            ).sort_index(axis=1)
            seed_count = int(pivot.shape[1])
            basin_variance = pivot.var(axis=1, ddof=0)
            basin_std = np.sqrt(basin_variance)
            basin_range = pivot.max(axis=1) - pivot.min(axis=1)
            observed_range = float(variant_frame[value_column].max() - variant_frame[value_column].min())
            range_scale_sq = observed_range**2 if observed_range > 0 else np.nan
            normalized_basin_variance = basin_variance / range_scale_sq

            for basin_id in pivot.index:
                basin_rows.append(
                    {
                        "variant": variant,
                        "parameter": parameter,
                        "basin_id": int(basin_id),
                        "seed_count": seed_count,
                        "basin_variance": float(basin_variance.loc[basin_id]),
                        "basin_std": float(basin_std.loc[basin_id]),
                        "basin_range": float(basin_range.loc[basin_id]),
                        "normalized_basin_variance": float(normalized_basin_variance.loc[basin_id]),
                    }
                )

            parameter_rows.append(
                {
                    "variant": variant,
                    "parameter": parameter,
                    "basin_count": int(len(pivot)),
                    "seed_count": seed_count,
                    "observed_range": observed_range,
                    "mean_basin_variance": float(basin_variance.mean()),
                    "median_basin_variance": float(basin_variance.median()),
                    "mean_basin_std": float(basin_std.mean()),
                    "median_basin_std": float(basin_std.median()),
                    "mean_basin_range": float(basin_range.mean()),
                    "median_basin_range": float(basin_range.median()),
                    "mean_normalized_basin_variance": float(normalized_basin_variance.mean()),
                    "median_normalized_basin_variance": float(normalized_basin_variance.median()),
                }
            )

    basin_table = pd.DataFrame(basin_rows).sort_values(
        ["variant", "parameter", "basin_id"]
    ).reset_index(drop=True)
    parameter_table = pd.DataFrame(parameter_rows).sort_values(
        ["parameter", "mean_normalized_basin_variance", "variant"]
    ).reset_index(drop=True)
    variant_table = (
        parameter_table.groupby("variant", as_index=False)
        .agg(
            parameter_count=("parameter", "nunique"),
            mean_of_mean_basin_variance=("mean_basin_variance", "mean"),
            median_of_mean_basin_variance=("mean_basin_variance", "median"),
            mean_of_mean_basin_std=("mean_basin_std", "mean"),
            mean_of_mean_normalized_basin_variance=(
                "mean_normalized_basin_variance",
                "mean",
            ),
            median_of_mean_normalized_basin_variance=(
                "mean_normalized_basin_variance",
                "median",
            ),
        )
        .sort_values("mean_of_mean_normalized_basin_variance")
        .reset_index(drop=True)
    )
    return basin_table, parameter_table, variant_table


def seedwise_spearman_table(
    parameter_frame: pd.DataFrame,
    attribute_frame: pd.DataFrame,
    parameter_names: list[str],
) -> pd.DataFrame:
    merged = parameter_frame.merge(attribute_frame, on="basin_id", how="inner")
    attribute_columns = [column for column in attribute_frame.columns if column != "basin_id"]

    rows: list[dict[str, float | int | str]] = []
    for (variant, seed), seed_frame in merged.groupby(["variant", "seed"]):
        for attribute in attribute_columns:
            attribute_values = seed_frame[attribute]
            for parameter in parameter_names:
                rho = attribute_values.corr(seed_frame[f"{parameter}_mean"], method="spearman")
                r2 = float(rho**2) if pd.notna(rho) else np.nan
                rows.append(
                    {
                        "variant": variant,
                        "seed": int(seed),
                        "attribute": attribute,
                        "parameter": parameter,
                        "spearman_rho": float(rho),
                        "spearman_r2": r2,
                        "abs_spearman_rho": float(abs(rho)) if pd.notna(rho) else np.nan,
                    }
                )
    return pd.DataFrame(rows).sort_values(
        ["variant", "attribute", "parameter", "seed"]
    ).reset_index(drop=True)


def summarize_pairwise_correlation_stability(
    seed_table: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    pair_table = (
        seed_table.groupby(["variant", "attribute", "parameter"], as_index=False)
        .agg(
            seed_count=("seed", "count"),
            mean_spearman_rho=("spearman_rho", "mean"),
            mean_abs_spearman_rho=("abs_spearman_rho", "mean"),
            variance_spearman_rho=("spearman_rho", lambda values: float(np.var(values, ddof=0))),
            std_spearman_rho=("spearman_rho", lambda values: float(np.std(values, ddof=0))),
            mean_spearman_r2=("spearman_r2", "mean"),
            variance_spearman_r2=("spearman_r2", lambda values: float(np.var(values, ddof=0))),
            std_spearman_r2=("spearman_r2", lambda values: float(np.std(values, ddof=0))),
            min_spearman_r2=("spearman_r2", "min"),
            max_spearman_r2=("spearman_r2", "max"),
            sign_consistency=("spearman_rho", sign_consistency_rate),
        )
        .reset_index(drop=True)
    )
    pair_table["range_spearman_r2"] = (
        pair_table["max_spearman_r2"] - pair_table["min_spearman_r2"]
    )

    variant_table = (
        pair_table.groupby("variant", as_index=False)
        .agg(
            pair_count=("parameter", "count"),
            mean_variance_spearman_r2=("variance_spearman_r2", "mean"),
            median_variance_spearman_r2=("variance_spearman_r2", "median"),
            p90_variance_spearman_r2=(
                "variance_spearman_r2",
                lambda values: float(np.quantile(values, 0.9)),
            ),
            max_variance_spearman_r2=("variance_spearman_r2", "max"),
            mean_range_spearman_r2=("range_spearman_r2", "mean"),
            mean_sign_consistency=("sign_consistency", "mean"),
        )
        .sort_values("mean_variance_spearman_r2")
        .reset_index(drop=True)
    )
    return pair_table, variant_table


def key_parameter_correlation_summary(
    seed_table: pd.DataFrame,
    pair_table: pd.DataFrame,
    key_parameters: list[str],
    top_k: int,
) -> pd.DataFrame:
    rows: list[dict[str, float | int | str]] = []

    for variant in VARIANT_ORDER:
        variant_seed = seed_table.loc[seed_table["variant"] == variant]
        variant_pair = pair_table.loc[pair_table["variant"] == variant]
        if variant_seed.empty or variant_pair.empty:
            continue

        for parameter in key_parameters:
            param_seed = variant_seed.loc[variant_seed["parameter"] == parameter]
            param_pair = variant_pair.loc[variant_pair["parameter"] == parameter]
            if param_seed.empty or param_pair.empty:
                continue

            ranking_by_seed: dict[int, list[str]] = {}
            for seed, seed_frame in param_seed.groupby("seed"):
                ordered = seed_frame.sort_values(
                    ["abs_spearman_rho", "attribute"],
                    ascending=[False, True],
                )["attribute"].tolist()
                ranking_by_seed[int(seed)] = ordered

            top_k_effective = min(top_k, param_seed["attribute"].nunique())
            rows.append(
                {
                    "variant": variant,
                    "parameter": parameter,
                    "seed_count": int(param_seed["seed"].nunique()),
                    "attribute_count": int(param_seed["attribute"].nunique()),
                    "top_k": int(top_k_effective),
                    "mean_abs_spearman_rho": float(param_pair["mean_abs_spearman_rho"].mean()),
                    "mean_spearman_r2": float(param_pair["mean_spearman_r2"].mean()),
                    "mean_variance_spearman_r2": float(param_pair["variance_spearman_r2"].mean()),
                    "median_variance_spearman_r2": float(param_pair["variance_spearman_r2"].median()),
                    "mean_sign_consistency": float(param_pair["sign_consistency"].mean()),
                    "share_all_sign_consistent": float((param_pair["sign_consistency"] >= 0.999999).mean()),
                    "topk_overlap_rate": mean_pairwise_topk_overlap(ranking_by_seed, top_k_effective),
                }
            )

    return pd.DataFrame(rows).sort_values(["parameter", "variant"]).reset_index(drop=True)


def method_consistency_summary(
    pair_table: pd.DataFrame,
    key_parameters: list[str],
    top_k: int,
) -> pd.DataFrame:
    rows: list[dict[str, float | int | str]] = []

    for parameter in key_parameters:
        param_table = pair_table.loc[pair_table["parameter"] == parameter].copy()
        if param_table.empty:
            continue

        rho_matrix = param_table.pivot(index="attribute", columns="variant", values="mean_spearman_rho")
        abs_rho_matrix = param_table.pivot(index="attribute", columns="variant", values="mean_abs_spearman_rho")
        available_variants = [variant for variant in VARIANT_ORDER if variant in rho_matrix.columns]

        ranked_attributes: dict[str, list[str]] = {}
        for variant in available_variants:
            ordered = (
                abs_rho_matrix[variant]
                .sort_values(ascending=False, kind="stable")
                .index.tolist()
            )
            ranked_attributes[variant] = ordered

        for variant_a, variant_b in itertools.combinations(available_variants, 2):
            aligned = rho_matrix[[variant_a, variant_b]].dropna()
            if aligned.empty:
                continue

            rows.append(
                {
                    "parameter": parameter,
                    "variant_a": variant_a,
                    "variant_b": variant_b,
                    "attribute_count": int(len(aligned)),
                    "pearson_corr_of_mean_rho": float(aligned[variant_a].corr(aligned[variant_b], method="pearson")),
                    "spearman_corr_of_mean_rho": float(aligned[variant_a].corr(aligned[variant_b], method="spearman")),
                    "mean_abs_diff_rho": float((aligned[variant_a] - aligned[variant_b]).abs().mean()),
                    "sign_agreement_rate": sign_agreement_rate(aligned[variant_a], aligned[variant_b]),
                    "topk_overlap_rate": overlap_rate(
                        ranked_attributes[variant_a],
                        ranked_attributes[variant_b],
                        min(top_k, len(aligned)),
                    ),
                }
            )

    return pd.DataFrame(rows).sort_values(
        ["parameter", "variant_a", "variant_b"]
    ).reset_index(drop=True)


def method_consistency_overall(method_summary: pd.DataFrame) -> pd.DataFrame:
    if method_summary.empty:
        return pd.DataFrame(
            columns=[
                "variant_a",
                "variant_b",
                "parameter_count",
                "mean_pearson_corr_of_mean_rho",
                "mean_spearman_corr_of_mean_rho",
                "mean_abs_diff_rho",
                "mean_sign_agreement_rate",
                "mean_topk_overlap_rate",
            ]
        )

    return (
        method_summary.groupby(["variant_a", "variant_b"], as_index=False)
        .agg(
            parameter_count=("parameter", "count"),
            mean_pearson_corr_of_mean_rho=("pearson_corr_of_mean_rho", "mean"),
            mean_spearman_corr_of_mean_rho=("spearman_corr_of_mean_rho", "mean"),
            mean_abs_diff_rho=("mean_abs_diff_rho", "mean"),
            mean_sign_agreement_rate=("sign_agreement_rate", "mean"),
            mean_topk_overlap_rate=("topk_overlap_rate", "mean"),
        )
        .sort_values(["variant_a", "variant_b"])
        .reset_index(drop=True)
    )


def focused_parameter_table(
    parameter_summary: pd.DataFrame,
    focus_parameter: str,
) -> pd.DataFrame:
    focused = parameter_summary.loc[parameter_summary["parameter"] == focus_parameter].copy()
    if focused.empty:
        raise ValueError(f"Focused parameter '{focus_parameter}' not found in parameter summary.")
    return focused.sort_values("mean_basin_variance").reset_index(drop=True)


def focused_correlation_table(
    pair_summary: pd.DataFrame,
    focus_parameter: str,
) -> pd.DataFrame:
    focused = pair_summary.loc[pair_summary["parameter"] == focus_parameter].copy()
    if focused.empty:
        raise ValueError(f"Focused parameter '{focus_parameter}' not found in correlation summary.")
    return focused.sort_values("variance_spearman_r2").reset_index(drop=True)


def plot_key_parameter_overview(
    summary: pd.DataFrame,
    key_parameters: list[str],
    output_path: Path,
    dpi: int,
) -> None:
    metric_specs = [
        ("mean_spearman_r2", "Mean R^2", "YlGnBu"),
        ("mean_variance_spearman_r2", "Var(R^2)", "YlOrRd"),
        ("mean_sign_consistency", "Sign Consistency", "GnBu"),
        ("topk_overlap_rate", "Top-k Overlap", "PuBuGn"),
    ]
    variants = [variant for variant in VARIANT_ORDER if variant in summary["variant"].unique()]

    fig, axes = plt.subplots(1, len(metric_specs), figsize=(4.2 * len(metric_specs), 1.0 + 0.68 * len(key_parameters)))
    if len(metric_specs) == 1:
        axes = [axes]

    for axis, (metric, title, cmap) in zip(axes, metric_specs):
        heatmap = (
            summary.pivot(index="parameter", columns="variant", values=metric)
            .reindex(index=key_parameters, columns=variants)
        )
        image = axis.imshow(heatmap.to_numpy(dtype=float), aspect="auto", cmap=cmap)
        axis.set_title(title)
        axis.set_xticks(np.arange(len(variants)))
        axis.set_xticklabels(variants, rotation=25, ha="right")
        axis.set_yticks(np.arange(len(key_parameters)))
        axis.set_yticklabels(key_parameters)

        for row_idx, parameter in enumerate(key_parameters):
            for col_idx, variant in enumerate(variants):
                value = heatmap.loc[parameter, variant]
                if pd.isna(value):
                    label = "NA"
                else:
                    label = f"{value:.3f}"
                axis.text(col_idx, row_idx, label, ha="center", va="center", fontsize=8, color="black")

        fig.colorbar(image, ax=axis, fraction=0.046, pad=0.04)

    fig.suptitle("Cross-seed correlation stability across key parameters", y=1.02)
    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def render_report(
    output_path: Path,
    focus_parameter: str,
    key_parameters: list[str],
    top_k: int,
    variant_parameter_summary: pd.DataFrame,
    variant_correlation_summary: pd.DataFrame,
    focus_parameter_variance: pd.DataFrame,
    focus_parameter_correlations: pd.DataFrame,
    key_parameter_summary: pd.DataFrame,
    method_consistency: pd.DataFrame,
    method_consistency_overall_summary: pd.DataFrame,
    sample_count_summary: dict[str, int],
) -> None:
    key_parameter_view = key_parameter_summary[
        [
            "parameter",
            "variant",
            "mean_spearman_r2",
            "mean_variance_spearman_r2",
            "mean_sign_consistency",
            "topk_overlap_rate",
        ]
    ].copy()

    lines = [
        "# Seed Stability Report",
        "",
        f"Focused parameter: `{focus_parameter}`",
        f"Key parameters: {', '.join(f'`{parameter}`' for parameter in key_parameters)}",
        f"Top-k overlap uses `k={top_k}` strongest attributes by absolute Spearman rho.",
        "",
        "## Overall parameter stability by method",
        "",
        variant_parameter_summary.to_string(index=False),
        "",
        "## Overall correlation R^2 stability by method",
        "",
        variant_correlation_summary.to_string(index=False),
        "",
        "## Sample-count validation",
        "",
        json.dumps(sample_count_summary, indent=2),
        "",
        f"## Basin variance summary for `{focus_parameter}`",
        "",
        focus_parameter_variance.to_string(index=False),
        "",
        f"## Lowest R^2 variance pairs for `{focus_parameter}`",
        "",
        focus_parameter_correlations.head(15).to_string(index=False),
        "",
        "## Key-parameter correlation stability overview",
        "",
        key_parameter_view.to_string(index=False),
        "",
        "## Cross-method consistency across key parameters",
        "",
        method_consistency.to_string(index=False),
        "",
        "## Overall cross-method consistency summary",
        "",
        method_consistency_overall_summary.to_string(index=False),
        "",
    ]
    output_path.write_text("\n".join(lines), encoding="utf-8")


def write_json_summary(
    output_path: Path,
    focus_parameter: str,
    key_parameters: list[str],
    top_k: int,
    variant_parameter_summary: pd.DataFrame,
    variant_correlation_summary: pd.DataFrame,
    focus_parameter_variance: pd.DataFrame,
    key_parameter_summary: pd.DataFrame,
    method_consistency: pd.DataFrame,
    method_consistency_overall_summary: pd.DataFrame,
    sample_count_summary: dict[str, int],
) -> None:
    payload = {
        "focus_parameter": focus_parameter,
        "key_parameters": key_parameters,
        "top_k": top_k,
        "sample_count_summary": sample_count_summary,
        "parameter_stability_ranking": variant_parameter_summary.to_dict(orient="records"),
        "correlation_r2_stability_ranking": variant_correlation_summary.to_dict(orient="records"),
        "focus_parameter_variance": focus_parameter_variance.to_dict(orient="records"),
        "key_parameter_correlation_summary": key_parameter_summary.to_dict(orient="records"),
        "method_consistency": method_consistency.to_dict(orient="records"),
        "method_consistency_overall": method_consistency_overall_summary.to_dict(orient="records"),
    }
    output_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def main() -> None:
    args = parse_args()
    parameter_csv = Path(args.parameter_csv).resolve()
    attribute_csv = Path(args.attribute_csv).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    parameter_frame = pd.read_csv(parameter_csv)
    attribute_frame = pd.read_csv(attribute_csv)
    sample_count_summary = validate_mc_dropout_sample_counts(
        parameter_frame=parameter_frame,
        min_samples=args.min_mc_samples,
    )
    parameter_names = infer_parameter_names(parameter_frame)
    focus_parameter = canonical_parameter_name(args.focus_parameter, parameter_names)
    key_parameters = parse_key_parameters(args.key_parameters, parameter_names)

    basin_table, parameter_summary, variant_parameter_summary = basin_variance_table(
        parameter_frame=parameter_frame,
        parameter_names=parameter_names,
    )
    seed_corr_table = seedwise_spearman_table(
        parameter_frame=parameter_frame,
        attribute_frame=attribute_frame,
        parameter_names=parameter_names,
    )
    pair_corr_summary, variant_correlation_summary = summarize_pairwise_correlation_stability(
        seed_corr_table
    )
    key_parameter_summary = key_parameter_correlation_summary(
        seed_table=seed_corr_table,
        pair_table=pair_corr_summary,
        key_parameters=key_parameters,
        top_k=args.top_k,
    )
    method_consistency = method_consistency_summary(
        pair_table=pair_corr_summary,
        key_parameters=key_parameters,
        top_k=args.top_k,
    )
    method_consistency_overall_summary = method_consistency_overall(method_consistency)

    focus_parameter_variance = focused_parameter_table(parameter_summary, focus_parameter)
    focus_parameter_correlations = focused_correlation_table(pair_corr_summary, focus_parameter)

    basin_table.to_csv(output_dir / "seed_parameter_variance_by_basin.csv", index=False)
    parameter_summary.to_csv(output_dir / "seed_parameter_variance_by_parameter.csv", index=False)
    variant_parameter_summary.to_csv(
        output_dir / "seed_parameter_variance_by_variant.csv",
        index=False,
    )
    seed_corr_table.to_csv(output_dir / "seed_correlation_r2_by_seed.csv", index=False)
    pair_corr_summary.to_csv(
        output_dir / "seed_correlation_r2_variance_by_pair.csv",
        index=False,
    )
    variant_correlation_summary.to_csv(
        output_dir / "seed_correlation_r2_variance_by_variant.csv",
        index=False,
    )
    key_parameter_summary.to_csv(
        output_dir / "key_parameter_correlation_stability_summary.csv",
        index=False,
    )
    method_consistency.to_csv(
        output_dir / "method_consistency_by_parameter.csv",
        index=False,
    )
    method_consistency_overall_summary.to_csv(
        output_dir / "method_consistency_overall.csv",
        index=False,
    )
    focus_parameter_variance.to_csv(
        output_dir / f"focus_parameter_variance_{focus_parameter}.csv",
        index=False,
    )
    focus_parameter_correlations.to_csv(
        output_dir / f"focus_parameter_correlation_r2_variance_{focus_parameter}.csv",
        index=False,
    )

    plot_key_parameter_overview(
        summary=key_parameter_summary,
        key_parameters=key_parameters,
        output_path=output_dir / "key_parameter_correlation_stability_overview.png",
        dpi=args.dpi,
    )

    render_report(
        output_path=output_dir / "seed_stability_report.md",
        focus_parameter=focus_parameter,
        key_parameters=key_parameters,
        top_k=args.top_k,
        variant_parameter_summary=variant_parameter_summary,
        variant_correlation_summary=variant_correlation_summary,
        focus_parameter_variance=focus_parameter_variance,
        focus_parameter_correlations=focus_parameter_correlations,
        key_parameter_summary=key_parameter_summary,
        method_consistency=method_consistency,
        method_consistency_overall_summary=method_consistency_overall_summary,
        sample_count_summary=sample_count_summary,
    )
    write_json_summary(
        output_path=output_dir / "seed_stability_summary.json",
        focus_parameter=focus_parameter,
        key_parameters=key_parameters,
        top_k=args.top_k,
        variant_parameter_summary=variant_parameter_summary,
        variant_correlation_summary=variant_correlation_summary,
        focus_parameter_variance=focus_parameter_variance,
        key_parameter_summary=key_parameter_summary,
        method_consistency=method_consistency,
        method_consistency_overall_summary=method_consistency_overall_summary,
        sample_count_summary=sample_count_summary,
    )


if __name__ == "__main__":
    main()
